public class LimitsWrapper {

    public AnalyticsExternalDataSizeMB AnalyticsExternalDataSizeMB;
    public CdpAiInferenceApiMonthlyLimit CdpAiInferenceApiMonthlyLimit;
    public ConcurrentAsyncGetReportInstances ConcurrentAsyncGetReportInstances;
    public ConcurrentEinsteinDataInsightsStoryCreation ConcurrentEinsteinDataInsightsStoryCreation;
    public ConcurrentEinsteinDiscoveryStoryCreation ConcurrentEinsteinDiscoveryStoryCreation;
    public ConcurrentSyncReportRuns ConcurrentSyncReportRuns;
    public ContentDistBandwidthLimitMB ContentDistBandwidthLimitMB;
    public ContentDistViewLimit ContentDistViewLimit;
    public ContentPublicationLimit ContentPublicationLimit;
    public DailyAnalyticsDataflowJobExecutions DailyAnalyticsDataflowJobExecutions;
    public DailyAnalyticsUploadedFilesSizeMB DailyAnalyticsUploadedFilesSizeMB;
    public DailyApexCursorLimit DailyApexCursorLimit;
    public DailyApexCursorRowsLimit DailyApexCursorRowsLimit;
    public DailyApexPCursorLimit DailyApexPCursorLimit;
    public DailyApiRequests DailyApiRequests;
    public DailyAsyncApexExecutions DailyAsyncApexExecutions;
    public DailyAsyncApexTests DailyAsyncApexTests;
    public DailyBulkApiBatches DailyBulkApiBatches;
    public DailyBulkV2QueryFileStorageMB DailyBulkV2QueryFileStorageMB;
    public DailyBulkV2QueryJobs DailyBulkV2QueryJobs;
    public DailyDeliveredPlatformEvents DailyDeliveredPlatformEvents;
    public DailyDurableGenericStreamingApiEvents DailyDurableGenericStreamingApiEvents;
    public DailyDurableStreamingApiEvents DailyDurableStreamingApiEvents;
    public DailyEinsteinDataInsightsStoryCreation DailyEinsteinDataInsightsStoryCreation;
    public DailyEinsteinDiscoveryOptimizationJobRuns DailyEinsteinDiscoveryOptimizationJobRuns;
    public DailyEinsteinDiscoveryPredictAPICalls DailyEinsteinDiscoveryPredictAPICalls;
    public DailyEinsteinDiscoveryPredictionsByCDC DailyEinsteinDiscoveryPredictionsByCDC;
    public DailyEinsteinDiscoveryStoryCreation DailyEinsteinDiscoveryStoryCreation;
    public DailyFunctionsApiCallLimit DailyFunctionsApiCallLimit;
    public DailyGenericStreamingApiEvents DailyGenericStreamingApiEvents;
    public DailyMetadataRetrievesWithDependencies DailyMetadataRetrievesWithDependencies;
    public DailyServiceEmailAgentforceCalls DailyServiceEmailAgentforceCalls;
    public DailyStandardVolumePlatformEvents DailyStandardVolumePlatformEvents;
    public DailyStreamingApiEvents DailyStreamingApiEvents;
    public DailyWorkflowEmails DailyWorkflowEmails;
    public DataStorageMB DataStorageMB;
    public DurableStreamingApiConcurrentClients DurableStreamingApiConcurrentClients;
    public ExternalServicesActiveObjects ExternalServicesActiveObjects;
    public ExternalServicesActiveOperations ExternalServicesActiveOperations;
    public ExternalServicesObjectProperties ExternalServicesObjectProperties;
    public ExternalServicesObjects ExternalServicesObjects;
    public ExternalServicesOperations ExternalServicesOperations;
    public ExternalServicesRegistrations ExternalServicesRegistrations;
    public FileStorageMB FileStorageMB;
    public HourlyAsyncReportRuns HourlyAsyncReportRuns;
    public HourlyDashboardRefreshes HourlyDashboardRefreshes;
    public HourlyDashboardResults HourlyDashboardResults;
    public HourlyDashboardStatuses HourlyDashboardStatuses;
    public HourlyElevateAsyncReportRuns HourlyElevateAsyncReportRuns;
    public HourlyElevateSyncReportRuns HourlyElevateSyncReportRuns;
    public HourlyLongTermIdMapping HourlyLongTermIdMapping;
    public HourlyManagedContentPublicRequests HourlyManagedContentPublicRequests;
    public HourlyODataCallout HourlyODataCallout;
    public HourlyPublishedPlatformEvents HourlyPublishedPlatformEvents;
    public HourlyPublishedStandardVolumePlatformEvents HourlyPublishedStandardVolumePlatformEvents;
    public HourlyShortTermIdMapping HourlyShortTermIdMapping;
    public HourlySyncReportRuns HourlySyncReportRuns;
    public HourlyTimeBasedWorkflow HourlyTimeBasedWorkflow;
    public MassEmail MassEmail;
    public MaxContentDocumentsLimit MaxContentDocumentsLimit;
    public MonthlyEinsteinDiscoveryStoryCreation MonthlyEinsteinDiscoveryStoryCreation;
    public Package2VersionCreates Package2VersionCreates;
    public Package2VersionCreatesWithoutValidation Package2VersionCreatesWithoutValidation;
    public PermissionSets PermissionSets;
    public PlatformEventTriggersWithParallelProcessing PlatformEventTriggersWithParallelProcessing;
    public PrivateConnectOutboundCalloutHourlyLimitMB PrivateConnectOutboundCalloutHourlyLimitMB;
    public PublishCallbackUsageInApex PublishCallbackUsageInApex;
    public ScheduledFlowRunLimit ScheduledFlowRunLimit;
    public ScheduledPathRunLimit ScheduledPathRunLimit;
    public SingleEmail SingleEmail;
    public StreamingApiConcurrentClients StreamingApiConcurrentClients;

    public class AnalyticsExternalDataSizeMB {
        public Integer Max;
        public Integer Remaining;
    }

    public class CdpAiInferenceApiMonthlyLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class ConcurrentAsyncGetReportInstances {
        public Integer Max;
        public Integer Remaining;
    }

    public class ConcurrentEinsteinDataInsightsStoryCreation {
        public Integer Max;
        public Integer Remaining;
    }

    public class ConcurrentEinsteinDiscoveryStoryCreation {
        public Integer Max;
        public Integer Remaining;
    }

    public class ConcurrentSyncReportRuns {
        public Integer Max;
        public Integer Remaining;
    }

    public class ContentDistBandwidthLimitMB {
        public Integer Max;
        public Integer Remaining;
    }

    public class ContentDistViewLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class ContentPublicationLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyAnalyticsDataflowJobExecutions {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyAnalyticsUploadedFilesSizeMB {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyApexCursorLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyApexCursorRowsLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyApexPCursorLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyApiRequests {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyAsyncApexExecutions {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyAsyncApexTests {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyBulkApiBatches {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyBulkV2QueryFileStorageMB {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyBulkV2QueryJobs {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyDeliveredPlatformEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyDurableGenericStreamingApiEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyDurableStreamingApiEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyEinsteinDataInsightsStoryCreation {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyEinsteinDiscoveryOptimizationJobRuns {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyEinsteinDiscoveryPredictAPICalls {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyEinsteinDiscoveryPredictionsByCDC {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyEinsteinDiscoveryStoryCreation {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyFunctionsApiCallLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyGenericStreamingApiEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyMetadataRetrievesWithDependencies {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyServiceEmailAgentforceCalls {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyStandardVolumePlatformEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyStreamingApiEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class DailyWorkflowEmails {
        public Integer Max;
        public Integer Remaining;
    }

    public class DataStorageMB {
        public Integer Max;
        public Integer Remaining;
    }

    public class DurableStreamingApiConcurrentClients {
        public Integer Max;
        public Integer Remaining;
    }

    public class ExternalServicesActiveObjects {
        public Integer Max;
        public Integer Remaining;
    }

    public class ExternalServicesActiveOperations {
        public Integer Max;
        public Integer Remaining;
    }

    public class ExternalServicesObjectProperties {
        public Integer Max;
        public Integer Remaining;
    }

    public class ExternalServicesObjects {
        public Integer Max;
        public Integer Remaining;
    }

    public class ExternalServicesOperations {
        public Integer Max;
        public Integer Remaining;
    }

    public class ExternalServicesRegistrations {
        public Integer Max;
        public Integer Remaining;
    }

    public class FileStorageMB {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyAsyncReportRuns {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyDashboardRefreshes {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyDashboardResults {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyDashboardStatuses {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyElevateAsyncReportRuns {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyElevateSyncReportRuns {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyLongTermIdMapping {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyManagedContentPublicRequests {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyODataCallout {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyPublishedPlatformEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyPublishedStandardVolumePlatformEvents {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyShortTermIdMapping {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlySyncReportRuns {
        public Integer Max;
        public Integer Remaining;
    }

    public class HourlyTimeBasedWorkflow {
        public Integer Max;
        public Integer Remaining;
    }

    public class MassEmail {
        public Integer Max;
        public Integer Remaining;
    }

    public class MaxContentDocumentsLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class MonthlyEinsteinDiscoveryStoryCreation {
        public Integer Max;
        public Integer Remaining;
    }

    public class Package2VersionCreates {
        public Integer Max;
        public Integer Remaining;
    }

    public class Package2VersionCreatesWithoutValidation {
        public Integer Max;
        public Integer Remaining;
    }

    public class CreateCustom {
        public Integer Max;
        public Integer Remaining;
    }

    public class PermissionSets {
        public Integer Max;
        public Integer Remaining;
        public CreateCustom CreateCustom;
    }

    public class PlatformEventTriggersWithParallelProcessing {
        public Integer Max;
        public Integer Remaining;
    }

    public class PrivateConnectOutboundCalloutHourlyLimitMB {
        public Integer Max;
        public Integer Remaining;
    }

    public class PublishCallbackUsageInApex {
        public Integer Max;
        public Integer Remaining;
    }

    public class ScheduledFlowRunLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class ScheduledPathRunLimit {
        public Integer Max;
        public Integer Remaining;
    }

    public class SingleEmail {
        public Integer Max;
        public Integer Remaining;
    }

    public class StreamingApiConcurrentClients {
        public Integer Max;
        public Integer Remaining;
    }
    public static LimitsWrapper parse(String json) {
        return (LimitsWrapper) System.JSON.deserialize(json, LimitsWrapper.class);
    }
}